apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deploy
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: bishnukashyap/java-web-app:15
        name: hello-app
        ports:
        - name: hello-app
          containerPort: 6000
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc
spec:
  ports:
    - name: helloport
      port: 6000
  type: LoadBalancer
  selector:
    app: hello-app
